name: padron_inventario_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  carousel_slider: ^4.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.1.0
  auto_route: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/fonts/Open_Sans/static/
    - assets/.env
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf