name: padron_inventario_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  carousel_slider: ^4.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
